---

- name: Deploy custom mimeapps
  template:
    src: templates/mimeapps.list.j2
    dest: "{{ mimeapps_user_home }}/.config/mimeapps.list"
    mode: 0664
    backup: yes
  become: true
  become_user: "{{ mimeapps_user }}"
